<?php

namespace Database\Seeders;

use App\Models\Cast;
use App\Models\Genre;
use App\Models\Movie;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run()
    {
        // ============================================================
        // CAST MEMBERS
        // ============================================================
        $castData = [
            'Robert Downey Jr.',
            'Scarlett Johansson',
            'Chris Evans',
            'Chris Hemsworth',
            'Tom Holland',
            'Zendaya',
            'Leonardo DiCaprio',
            'Margot Robbie',
            'Keanu Reeves',
            'Carrie-Anne Moss',
            'Timothée Chalamet',
            'Florence Pugh',
            'Cillian Murphy',
            'Emily Blunt',
            'Ryan Gosling',
            'Ana de Armas',
            'Tom Hanks',
            'Brad Pitt',
            'Joaquin Phoenix',
            'Anya Taylor-Joy',
            'Iko Uwais',
            'Joe Taslim',
            'Reza Rahadian',
            'Dian Sastrowardoyo',
            'Nicholas Saputra',
            'Raline Shah',
            'Shenina Cinnamon',
            'Angga Yunanda',
            'Morgan Freeman',
            'Matt Damon',
            'Christian Bale',
            'Heath Ledger',
            'Will Smith',
            'Samuel L. Jackson',
            'Clint Eastwood',
            'Harrison Ford',
            'Sigourney Weaver',
            'Jason Statham',
            'Liam Neeson',
            'Charlize Theron',
        ];

        $castMap = [];
        foreach ($castData as $name) {
            $castMap[$name] = Cast::updateOrCreate(['name' => $name])->id;
        }

        // ============================================================
        // MOVIES DATA
        // ============================================================
        $movies = [
            // ── POPULAR ─────────────────────────────────────────────
            [
                'title' => 'The Avengers',
                'original_title' => 'The Avengers',
                'overview' => "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
                'poster_path' => 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg',
                'release_date' => '2012-05-04',
                'vote_average' => 7.7,
                'vote_count' => 28000,
                'popularity' => 120.5,
                'is_popular' => true,
                'is_trending' => false,
                'youtube_key' => 'eOrNdBpGMv8',
                'genres' => ['action', 'adventure', 'science-fiction'],
                'casts' => [
                    ['name' => 'Robert Downey Jr.', 'character' => 'Tony Stark / Iron Man'],
                    ['name' => 'Scarlett Johansson', 'character' => 'Natasha Romanoff / Black Widow'],
                    ['name' => 'Chris Evans', 'character' => 'Steve Rogers / Captain America'],
                    ['name' => 'Chris Hemsworth', 'character' => 'Thor'],
                    ['name' => 'Samuel L. Jackson', 'character' => 'Nick Fury'],
                ],
            ],
            [
                'title' => 'Inception',
                'original_title' => 'Inception',
                'overview' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
                'release_date' => '2010-07-16',
                'vote_average' => 8.4,
                'vote_count' => 35000,
                'popularity' => 110.3,
                'is_popular' => true,
                'is_trending' => false,
                'youtube_key' => 'YoHD9XEInc0',
                'genres' => ['action', 'science-fiction', 'thriller'],
                'casts' => [
                    ['name' => 'Leonardo DiCaprio', 'character' => 'Dom Cobb'],
                    ['name' => 'Tom Hardy', 'character' => 'Eames'],
                    ['name' => 'Cillian Murphy', 'character' => 'Robert Fischer'],
                ],
            ],
            [
                'title' => 'Spider-Man: No Way Home',
                'original_title' => 'Spider-Man: No Way Home',
                'overview' => "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous.",
                'poster_path' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
                'release_date' => '2021-12-17',
                'vote_average' => 8.0,
                'vote_count' => 18000,
                'popularity' => 135.8,
                'is_popular' => true,
                'is_trending' => true,
                'youtube_key' => 'JfVOs4VSpmA',
                'genres' => ['action', 'adventure', 'science-fiction'],
                'casts' => [
                    ['name' => 'Tom Holland', 'character' => 'Peter Parker / Spider-Man'],
                    ['name' => 'Zendaya', 'character' => 'MJ'],
                ],
            ],
            [
                'title' => 'Oppenheimer',
                'original_title' => 'Oppenheimer',
                'overview' => 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxe0Ym3VCuZgLRN7.jpg',
                'release_date' => '2023-07-21',
                'vote_average' => 8.1,
                'vote_count' => 8500,
                'popularity' => 145.2,
                'is_popular' => true,
                'is_trending' => true,
                'youtube_key' => 'uYPbbksJxIg',
                'genres' => ['drama', 'history', 'thriller'],
                'casts' => [
                    ['name' => 'Cillian Murphy', 'character' => 'J. Robert Oppenheimer'],
                    ['name' => 'Emily Blunt', 'character' => 'Kitty Oppenheimer'],
                    ['name' => 'Robert Downey Jr.', 'character' => 'Lewis Strauss'],
                    ['name' => 'Matt Damon', 'character' => 'General Leslie Groves'],
                    ['name' => 'Florence Pugh', 'character' => 'Jean Tatlock'],
                ],
            ],
            [
                'title' => 'Dune: Part Two',
                'original_title' => 'Dune: Part Two',
                'overview' => 'Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
                'release_date' => '2024-03-01',
                'vote_average' => 8.2,
                'vote_count' => 6200,
                'popularity' => 155.7,
                'is_popular' => true,
                'is_trending' => true,
                'youtube_key' => 'Way9Dexny3w',
                'genres' => ['science-fiction', 'adventure', 'drama'],
                'casts' => [
                    ['name' => 'Timothée Chalamet', 'character' => 'Paul Atreides'],
                    ['name' => 'Zendaya', 'character' => 'Chani'],
                    ['name' => 'Florence Pugh', 'character' => 'Princess Irulan'],
                ],
            ],

            // ── TRENDING ────────────────────────────────────────────
            [
                'title' => 'The Dark Knight',
                'original_title' => 'The Dark Knight',
                'overview' => 'When the menace known as the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nUIhs.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg',
                'release_date' => '2008-07-18',
                'vote_average' => 8.5,
                'vote_count' => 31000,
                'popularity' => 95.1,
                'is_popular' => false,
                'is_trending' => true,
                'youtube_key' => 'EXeTwQWrcwY',
                'genres' => ['action', 'crime', 'drama', 'thriller'],
                'casts' => [
                    ['name' => 'Christian Bale', 'character' => 'Bruce Wayne / Batman'],
                    ['name' => 'Heath Ledger', 'character' => 'The Joker'],
                    ['name' => 'Morgan Freeman', 'character' => 'Lucius Fox'],
                ],
            ],
            [
                'title' => 'The Matrix',
                'original_title' => 'The Matrix',
                'overview' => 'A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
                'release_date' => '1999-03-31',
                'vote_average' => 8.2,
                'vote_count' => 24000,
                'popularity' => 85.0,
                'is_popular' => false,
                'is_trending' => true,
                'youtube_key' => 'vKQi3bBA1y8',
                'genres' => ['action', 'science-fiction'],
                'casts' => [
                    ['name' => 'Keanu Reeves', 'character' => 'Thomas A. Anderson / Neo'],
                    ['name' => 'Carrie-Anne Moss', 'character' => 'Trinity'],
                ],
            ],
            [
                'title' => 'John Wick: Chapter 4',
                'original_title' => 'John Wick: Chapter 4',
                'overview' => 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7LsyF7OE6Viz.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/7LxL6rg4kh9D7L6JMViHVJnNZ7.jpg',
                'release_date' => '2023-03-24',
                'vote_average' => 7.8,
                'vote_count' => 5800,
                'popularity' => 100.3,
                'is_popular' => true,
                'is_trending' => true,
                'youtube_key' => 'qEVUtrk8_B4',
                'genres' => ['action', 'thriller', 'crime'],
                'casts' => [
                    ['name' => 'Keanu Reeves', 'character' => 'John Wick'],
                ],
            ],

            // ── COMEDY ──────────────────────────────────────────────
            [
                'title' => 'The Grand Budapest Hotel',
                'original_title' => 'The Grand Budapest Hotel',
                'overview' => 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/eWDyYq6JdnhVfarGJcqbiMcjfbb.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/nX5XotM9yprCKarRH4fzOq1VM1J.jpg',
                'release_date' => '2014-03-28',
                'vote_average' => 8.1,
                'vote_count' => 16200,
                'popularity' => 65.3,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => '1Fg5iWmQjwk',
                'genres' => ['comedy', 'drama', 'crime'],
                'casts' => [],
            ],
            [
                'title' => 'Barbie',
                'original_title' => 'Barbie',
                'overview' => 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
                'release_date' => '2023-07-21',
                'vote_average' => 7.0,
                'vote_count' => 7200,
                'popularity' => 88.4,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'pBk4NYhWNMM',
                'genres' => ['comedy', 'adventure', 'fantasy'],
                'casts' => [
                    ['name' => 'Margot Robbie', 'character' => 'Barbie'],
                    ['name' => 'Ryan Gosling', 'character' => 'Ken'],
                ],
            ],
            [
                'title' => 'Free Guy',
                'original_title' => 'Free Guy',
                'overview' => 'A bank teller discovers he is actually a background player in an open-world video game, and decides to become the hero of his own story.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm52KFQo.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/j28p5VwI5ieZnNwfeuZ5Ve3mPsn.jpg',
                'release_date' => '2021-08-13',
                'vote_average' => 7.2,
                'vote_count' => 8100,
                'popularity' => 72.6,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'X2m-08cOAbc',
                'genres' => ['comedy', 'action', 'adventure', 'science-fiction'],
                'casts' => [],
            ],
            [
                'title' => 'Knives Out',
                'original_title' => 'Knives Out',
                'overview' => 'When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
                'release_date' => '2019-11-27',
                'vote_average' => 7.9,
                'vote_count' => 11400,
                'popularity' => 78.1,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'xi-1NchUqMA',
                'genres' => ['comedy', 'crime', 'mystery'],
                'casts' => [
                    ['name' => 'Ana de Armas', 'character' => 'Marta Cabrera'],
                ],
            ],

            // ── ACTION ──────────────────────────────────────────────
            [
                'title' => 'Mad Max: Fury Road',
                'original_title' => 'Mad Max: Fury Road',
                'overview' => 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg',
                'release_date' => '2015-05-15',
                'vote_average' => 7.6,
                'vote_count' => 21500,
                'popularity' => 80.2,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'hEJnMQG9ev8',
                'genres' => ['action', 'adventure', 'science-fiction'],
                'casts' => [
                    ['name' => 'Charlize Theron', 'character' => 'Imperator Furiosa'],
                    ['name' => 'Tom Hardy', 'character' => 'Max Rockatansky'],
                ],
            ],
            [
                'title' => 'Top Gun: Maverick',
                'original_title' => 'Top Gun: Maverick',
                'overview' => 'After more than thirty years of service as one of the Navy\'s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/AaV1YIdWKRiEHuGIVsOLOHkEuFp.jpg',
                'release_date' => '2022-05-27',
                'vote_average' => 8.3,
                'vote_count' => 8900,
                'popularity' => 92.4,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'qSqVVswa420',
                'genres' => ['action', 'drama'],
                'casts' => [],
            ],
            [
                'title' => 'The Raid',
                'original_title' => 'Serbuan Maut',
                'overview' => 'A S.W.A.T. team becomes trapped in a tenement run by a ruthless mobster and his army of killers and thugs in Jakarta, Indonesia.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/kMnJROJEnb51mMRQBqBJVJTF1JR.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/qdBqZwjId8e7V1HV5AI3QHHaRT3.jpg',
                'release_date' => '2011-09-08',
                'vote_average' => 7.6,
                'vote_count' => 3200,
                'popularity' => 55.0,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'PkULMOFpuCo',
                'genres' => ['action', 'crime', 'thriller'],
                'casts' => [
                    ['name' => 'Iko Uwais', 'character' => 'Rama'],
                    ['name' => 'Joe Taslim', 'character' => 'Jaka'],
                ],
            ],
            [
                'title' => 'The Raid 2',
                'original_title' => 'The Raid 2: Berandal',
                'overview' => 'After fighting his way out of a building filled with gangsters and madmen, Rama goes undercover with the thugs of Jakarta and plans to bring down the syndicate.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/FidOt56VPEBpjIr0dIWh5DZJdFp.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/vVoHhF0p5l7rHYBNJPbi8dUMq79.jpg',
                'release_date' => '2014-03-28',
                'vote_average' => 7.8,
                'vote_count' => 2800,
                'popularity' => 48.5,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'MjGaEH_lqGY',
                'genres' => ['action', 'crime', 'thriller'],
                'casts' => [
                    ['name' => 'Iko Uwais', 'character' => 'Rama'],
                ],
            ],

            // ── WESTERN ─────────────────────────────────────────────
            [
                'title' => 'Django Unchained',
                'original_title' => 'Django Unchained',
                'overview' => 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg',
                'release_date' => '2012-12-25',
                'vote_average' => 8.2,
                'vote_count' => 25500,
                'popularity' => 77.5,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => '0fUCuvNlOCg',
                'genres' => ['western', 'drama', 'action'],
                'casts' => [
                    ['name' => 'Leonardo DiCaprio', 'character' => 'Calvin Candie'],
                    ['name' => 'Samuel L. Jackson', 'character' => 'Stephen'],
                ],
            ],
            [
                'title' => 'The Good, the Bad and the Ugly',
                'original_title' => 'Il buono, il brutto, il cattivo',
                'overview' => 'While the Civil War rages between Union and Confederacy, three men – a quiet loner, a ruthless hit man, and a Mexican bandit – comb the American Southwest in search of a strongbox containing 200,000 in gold.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/wTOMho8AtLfM4pLq8K7x0Jd8Uts.jpg',
                'release_date' => '1966-12-23',
                'vote_average' => 8.5,
                'vote_count' => 8100,
                'popularity' => 60.3,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'WCN5JJY_wiA',
                'genres' => ['western'],
                'casts' => [
                    ['name' => 'Clint Eastwood', 'character' => 'Blondie / The Good'],
                ],
            ],
            [
                'title' => 'Unforgiven',
                'original_title' => 'Unforgiven',
                'overview' => 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/jj3JxhTnufYSJJ1RsB8NkoLkXAz.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/6RnJrtRMgGfngJuUADlWNqpXdNZ.jpg',
                'release_date' => '1992-08-07',
                'vote_average' => 7.9,
                'vote_count' => 4300,
                'popularity' => 42.1,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'E8fIF2yfikE',
                'genres' => ['western', 'drama'],
                'casts' => [
                    ['name' => 'Clint Eastwood', 'character' => 'William Munny'],
                    ['name' => 'Morgan Freeman', 'character' => 'Ned Logan'],
                ],
            ],
            [
                'title' => 'True Grit',
                'original_title' => 'True Grit',
                'overview' => 'A stubborn teenager enlists the help of a tough U.S. Marshal to track down her father\'s murderer.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/er5sFMsJIqwirzUNI7TpUmMo5nN.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/ywDIqb0f2pNnXZwBDYQB2MVqvQY.jpg',
                'release_date' => '2010-12-22',
                'vote_average' => 7.4,
                'vote_count' => 5400,
                'popularity' => 38.9,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'aPbbXoGCxnM',
                'genres' => ['western', 'drama', 'adventure'],
                'casts' => [
                    ['name' => 'Matt Damon', 'character' => 'LaBoeuf'],
                ],
            ],

            // ── HORROR ──────────────────────────────────────────────
            [
                'title' => 'A Quiet Place',
                'original_title' => 'A Quiet Place',
                'overview' => 'A family is forced to live in silence while hiding from creatures that hunt by sound.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/roYyPiQDQKmIKUEhO912jvscOni.jpg',
                'release_date' => '2018-04-06',
                'vote_average' => 7.4,
                'vote_count' => 12200,
                'popularity' => 70.8,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'WR7cc5t7tv8',
                'genres' => ['horror', 'thriller', 'drama', 'science-fiction'],
                'casts' => [
                    ['name' => 'Emily Blunt', 'character' => 'Evelyn Abbott'],
                ],
            ],
            [
                'title' => 'Get Out',
                'original_title' => 'Get Out',
                'overview' => 'Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family\'s overly accommodating behavior as nervous attempts to deal with their daughter\'s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3zy7uCiqrmopQ3cr.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/t3LicFpYHeYpwqm7L5wDnDP0TuK.jpg',
                'release_date' => '2017-02-24',
                'vote_average' => 7.6,
                'vote_count' => 14800,
                'popularity' => 62.5,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'DzfpyUB60YY',
                'genres' => ['horror', 'mystery', 'thriller'],
                'casts' => [],
            ],
            [
                'title' => 'Hereditary',
                'original_title' => 'Hereditary',
                'overview' => 'When Ellen, the matriarch of the Graham family, passes away, her daughter\'s family begins to unravel cryptic and increasingly terrifying secrets about their ancestry.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/4GFPuL14eXi9PFCSsU6OmIRBeoZ.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/5GbkL1VMmvB3TsnMJDJm0hUswFZ.jpg',
                'release_date' => '2018-06-08',
                'vote_average' => 7.3,
                'vote_count' => 8700,
                'popularity' => 55.6,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'V6wWKNij_1M',
                'genres' => ['horror', 'mystery', 'thriller', 'drama'],
                'casts' => [],
            ],
            [
                'title' => 'Pengabdi Setan',
                'original_title' => 'Pengabdi Setan',
                'overview' => 'A woman who had been ill for a long time dies and her family begins to experience terrifying events connected to her past.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/rCR8TYQx6Y0V8O0WHjlrVfZW2KC.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/7bIlsJmeFQ6fJZdyIiNWbKM31v6.jpg',
                'release_date' => '2017-09-28',
                'vote_average' => 7.0,
                'vote_count' => 430,
                'popularity' => 35.2,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'NbFtVVnQjt8',
                'genres' => ['horror', 'mystery'],
                'casts' => [],
            ],

            // ── THRILLER ────────────────────────────────────────────
            [
                'title' => 'Joker',
                'original_title' => 'Joker',
                'overview' => 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
                'release_date' => '2019-10-04',
                'vote_average' => 8.2,
                'vote_count' => 23400,
                'popularity' => 105.8,
                'is_popular' => true,
                'is_trending' => false,
                'youtube_key' => 'zAGVQLHvwOY',
                'genres' => ['thriller', 'crime', 'drama'],
                'casts' => [
                    ['name' => 'Joaquin Phoenix', 'character' => 'Arthur Fleck / Joker'],
                ],
            ],
            [
                'title' => 'Parasite',
                'original_title' => 'Gisaengchung',
                'overview' => 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
                'release_date' => '2019-05-30',
                'vote_average' => 8.5,
                'vote_count' => 17200,
                'popularity' => 98.7,
                'is_popular' => true,
                'is_trending' => false,
                'youtube_key' => '5xH0HfJHsaY',
                'genres' => ['thriller', 'comedy', 'drama'],
                'casts' => [],
            ],
            [
                'title' => 'Gone Girl',
                'original_title' => 'Gone Girl',
                'overview' => 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight cast on him when suspicion arises that he may not be innocent.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/lv5xShBIDPe7m7J1TwJnQfvEFlE.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/hVd6VlhSjsT9X6RrjT0qzK1h0E3.jpg',
                'release_date' => '2014-10-03',
                'vote_average' => 7.9,
                'vote_count' => 13600,
                'popularity' => 68.9,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => '2-_-1nJf8HQ',
                'genres' => ['thriller', 'mystery', 'drama'],
                'casts' => [],
            ],
            [
                'title' => 'Shutter Island',
                'original_title' => 'Shutter Island',
                'overview' => 'Two U.S. Marshals are sent to investigate the disappearance of a patient from a hospital for the criminally insane on a remote island.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/kve20tXMHZp6x96AX1pMouBYRSV.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/3E2E4LnnO5FCmMn87EbnB2MRa7C.jpg',
                'release_date' => '2010-02-19',
                'vote_average' => 8.2,
                'vote_count' => 21800,
                'popularity' => 89.4,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => '5iaYLCiq5RM',
                'genres' => ['thriller', 'mystery', 'drama'],
                'casts' => [
                    ['name' => 'Leonardo DiCaprio', 'character' => 'Teddy Daniels'],
                ],
            ],

            // ── ANIMATION ───────────────────────────────────────────
            [
                'title' => 'Spider-Man: Into the Spider-Verse',
                'original_title' => 'Spider-Man: Into the Spider-Verse',
                'overview' => 'Miles Morales becomes the Spider-Man of his universe and crosses paths with five spider-powered counterparts from other dimensions to stop a threat to all realities.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/lrzGBsmM5b8kHr3hmpTEkpfqv3m.jpg',
                'release_date' => '2018-12-14',
                'vote_average' => 8.4,
                'vote_count' => 13400,
                'popularity' => 82.7,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'g4Hbz2jLxvQ',
                'genres' => ['animation', 'action', 'adventure', 'science-fiction'],
                'casts' => [],
            ],
            [
                'title' => 'Coco',
                'original_title' => 'Coco',
                'overview' => 'Despite his family\'s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the Land of the Dead.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
                'release_date' => '2017-11-22',
                'vote_average' => 8.2,
                'vote_count' => 18300,
                'popularity' => 75.4,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'Rvr68ASeQvQ',
                'genres' => ['animation', 'family', 'music', 'fantasy'],
                'casts' => [],
            ],
            [
                'title' => 'Spirited Away',
                'original_title' => 'Sen to Chihiro no Kamikakushi',
                'overview' => 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free herself and her family.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
                'release_date' => '2001-07-20',
                'vote_average' => 8.5,
                'vote_count' => 15200,
                'popularity' => 70.0,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'ByXuk9QqQkk',
                'genres' => ['animation', 'family', 'fantasy'],
                'casts' => [],
            ],
            [
                'title' => 'Your Name',
                'original_title' => 'Kimi no Na wa.',
                'overview' => 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6aYsPTRoBhql.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/dIWwZW7dJJtqC6CgWzYkNVKIUm2.jpg',
                'release_date' => '2016-08-26',
                'vote_average' => 8.6,
                'vote_count' => 10800,
                'popularity' => 68.2,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'xU47nhruN-Q',
                'genres' => ['animation', 'romance', 'drama'],
                'casts' => [],
            ],

            // ── INDONESIAN MOVIES ───────────────────────────────────
            [
                'title' => 'Habibie & Ainun',
                'original_title' => 'Habibie & Ainun',
                'overview' => 'The love story of Indonesia\'s third president B.J. Habibie and his wife Ainun, from their first meeting to their enduring love through political upheaval.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/mJzKgR5FqqPCLTkTqfk60Grvjmx.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/mJzKgR5FqqPCLTkTqfk60Grvjmx.jpg',
                'release_date' => '2012-12-20',
                'vote_average' => 7.5,
                'vote_count' => 210,
                'popularity' => 30.5,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'gQ6suu_MVKU',
                'genres' => ['drama', 'romance', 'history'],
                'casts' => [
                    ['name' => 'Reza Rahadian', 'character' => 'B.J. Habibie'],
                ],
            ],
            [
                'title' => 'AADC 2',
                'original_title' => 'Ada Apa Dengan Cinta? 2',
                'overview' => 'Cinta and Rangga meet again in Yogyakarta after being separated for years. Together they explore the city while revisiting mistakes from the past in hope of reconciliation.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/rHFRJwI8OHlCQtFHQhk2DRHKY2O.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/rHFRJwI8OHlCQtFHQhk2DRHKY2O.jpg',
                'release_date' => '2016-04-28',
                'vote_average' => 7.2,
                'vote_count' => 150,
                'popularity' => 28.0,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'FGMxIXaS2xo',
                'genres' => ['drama', 'romance'],
                'casts' => [
                    ['name' => 'Dian Sastrowardoyo', 'character' => 'Cinta'],
                    ['name' => 'Nicholas Saputra', 'character' => 'Rangga'],
                ],
            ],
            [
                'title' => 'Laskar Pelangi',
                'original_title' => 'Laskar Pelangi',
                'overview' => 'Inspired by a true story, this film follows a group of school children from a poor village in Belitung Island who struggle to pursue education against all odds.',
                'poster_path' => 'https://image.tmdb.org/t/p/w500/p05YNnHjQKDzwIBqfFSkqwQPLNP.jpg',
                'backdrop_path' => 'https://image.tmdb.org/t/p/w1280/p05YNnHjQKDzwIBqfFSkqwQPLNP.jpg',
                'release_date' => '2008-09-25',
                'vote_average' => 7.6,
                'vote_count' => 180,
                'popularity' => 25.0,
                'is_popular' => false,
                'is_trending' => false,
                'youtube_key' => 'U-vvOyRWBB4',
                'genres' => ['drama', 'family'],
                'casts' => [],
            ],
        ];

        // ============================================================
        // INSERT MOVIES
        // ============================================================
        foreach ($movies as $movieData) {
            $genreSlugs = $movieData['genres'] ?? [];
            $castEntries = $movieData['casts'] ?? [];

            unset($movieData['genres'], $movieData['casts']);

            $movie = Movie::updateOrCreate(
                ['title' => $movieData['title']],
                $movieData
            );

            // Attach genres
            $genreIds = Genre::whereIn('slug', $genreSlugs)->pluck('id')->toArray();
            $movie->genres()->sync($genreIds);

            // Attach casts
            $castSync = [];
            foreach ($castEntries as $index => $entry) {
                $castName = $entry['name'];
                if (isset($castMap[$castName])) {
                    $castSync[$castMap[$castName]] = [
                        'character' => $entry['character'] ?? null,
                        'order' => $index,
                    ];
                }
            }
            $movie->castMembers()->sync($castSync);
        }
    }
}
