<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use App\Services\Audit\AuditLogger;
use App\Support\SecurityEvents;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\Response;

/**
 * Records rate-limit rejections (HTTP 429) to audit_logs.
 *
 * Sits as a global middleware so it sees every response, including ones
 * generated by the throttle middleware further down the pipeline. When
 * the response carries a 429 status it writes one row per hit with:
 *
 *   action       = 'rate_limit.hit'
 *   meta.route   = matched route name (or path if unnamed)
 *   meta.method  = HTTP verb
 *   meta.path    = full request path
 *   meta.limiter = the throttle middleware argument that fired (best-effort)
 *   meta.retry_after = seconds (from the Retry-After header)
 *
 * Disable by flipping config('security.rate_limit_audit.enabled') to false
 * in environments that get hammered by crawlers (otherwise audit_logs
 * grows quickly with low-signal rows).
 *
 * Failures inside the auditing path are swallowed — we never want to
 * convert a 429 into a 500 just because audit logging blew up.
 */
final class RecordRateLimitHits
{
    public function __construct(private readonly AuditLogger $audit)
    {
    }

    public function handle(Request $request, Closure $next): Response
    {
        /** @var Response $response */
        $response = $next($request);

        if (! $this->shouldRecord($response)) {
            return $response;
        }

        try {
            // Routed through ::security() so the row is flagged is_security
            // AND a SecurityEventLogged event fires. The constant value is
            // 'security.rate_limit_hit' (the previous "rate_limit.hit" string
            // is preserved in legacy rows; new rows use the canonical name).
            $this->audit->security(
                event: SecurityEvents::RATE_LIMIT_HIT,
                subject: null,
                meta: $this->buildMeta($request, $response),
            );
        } catch (\Throwable $e) {
            // Audit failures must never break the request — log to the
            // dedicated security channel and move on.
            Log::channel('security')->warning('RecordRateLimitHits: audit write failed', [
                'message' => $e->getMessage(),
                'path' => $request->path(),
            ]);
        }

        return $response;
    }

    private function shouldRecord(Response $response): bool
    {
        if ($response->getStatusCode() !== 429) {
            return false;
        }

        return (bool) config('security.rate_limit_audit.enabled', true);
    }

    /**
     * @return array<string, mixed>
     */
    private function buildMeta(Request $request, Response $response): array
    {
        $route = $request->route();
        $routeName = $route instanceof Route ? $route->getName() : null;

        return [
            'route' => $routeName ?: $request->path(),
            'method' => $request->getMethod(),
            'path' => '/'.ltrim($request->path(), '/'),
            'limiter' => $this->extractLimiterName($route),
            'retry_after' => (int) ($response->headers->get('Retry-After') ?? 0),
        ];
    }

    /**
     * Best-effort extraction of which named limiter fired. Returns the
     * argument from any `throttle:<name>` middleware on the matched route.
     * Falls back to the literal middleware string when no colon is present
     * (e.g. global 'throttle:api') or null when the route is unmatched.
     */
    private function extractLimiterName(?Route $route): ?string
    {
        if (! $route instanceof Route) {
            return null;
        }

        foreach ($route->gatherMiddleware() as $middleware) {
            if (! is_string($middleware)) {
                continue;
            }
            if (! str_starts_with($middleware, 'throttle')) {
                continue;
            }

            return str_contains($middleware, ':')
                ? substr($middleware, strpos($middleware, ':') + 1)
                : $middleware;
        }

        return null;
    }
}
