<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * movie_quiz_questions
 * --------------------------------------------------------------------------
 * AI-generated multiple-choice trivia questions per movie. One movie has
 * many questions (typically ~10). Idempotently regenerated by
 * QuizQuestionGenerator (delete-by-movie + bulk insert in transaction).
 *
 * `correct_option` stores a single char 'a'|'b'|'c'|'d' matching one of
 * option_a..option_d. `explanation` is optional copy shown on the result
 * screen so users learn from wrong answers.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('movie_quiz_questions')) {
            return;
        }

        Schema::create('movie_quiz_questions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('movie_id')->constrained()->cascadeOnDelete();

            $table->text('question');
            $table->string('option_a');
            $table->string('option_b');
            $table->string('option_c');
            $table->string('option_d');

            // single char a/b/c/d — kept as CHAR(1) for compactness
            $table->char('correct_option', 1);

            $table->text('explanation')->nullable();

            $table->enum('difficulty', ['easy', 'medium', 'hard'])->default('medium');

            $table->timestamp('generated_at')->nullable();
            $table->timestamps();

            $table->index('movie_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('movie_quiz_questions');
    }
};
