<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Refer-a-friend bootstrap on the users table.
 *
 * Each user owns a stable 12-char `referral_code` (auto-generated by
 * {@see \App\Observers\UserObserver} on `created`). The string lives in
 * its own column so we never need to compute it at request time and so
 * the share link `/r/{code}` can be served from a CDN cache.
 *
 * `referred_by_user_id` records WHO referred this user. ON DELETE SET NULL
 * is deliberate — when a referrer deletes their account we keep the
 * referred user but drop the back-edge so the audit trail doesn't dangle
 * to a missing row.
 *
 * `referrals_count` and `referrals_rewards_earned` are denormalised
 * counters bumped by {@see \App\Services\Referrals\ReferralService}.
 * They're rebuildable from the conversions table at any time, so a
 * miscount is annoying but not fatal — they exist purely so the
 * dashboard hero ("you've referred X friends") doesn't have to COUNT()
 * across a potentially-large ledger on every page load.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            // 12-char nullable + unique. The observer back-fills on create
            // so the column should never stay NULL on a fresh row — but
            // legacy users will be NULL until they hit the dashboard once
            // (the trait lazy-generates).
            $table->string('referral_code', 12)->nullable()->unique()->after('username');

            $table->foreignId('referred_by_user_id')
                ->nullable()
                ->after('referral_code')
                ->constrained('users')
                ->nullOnDelete();

            $table->unsignedInteger('referrals_count')->default(0)->after('referred_by_user_id');
            $table->unsignedInteger('referrals_rewards_earned')->default(0)->after('referrals_count');
        });
    }

    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropForeign(['referred_by_user_id']);
            $table->dropColumn([
                'referral_code',
                'referred_by_user_id',
                'referrals_count',
                'referrals_rewards_earned',
            ]);
        });
    }
};
