<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

/**
 * BlogPost — editorial article.
 *
 * Lifecycle: draft → scheduled → published → archived.
 *   - `body` holds the markdown source (always authoritative).
 *   - `body_html` is the rendered cache, regenerated by setBodyAttribute()
 *     on every save (and BlogService::markdownToHtml when called externally).
 *   - `reading_minutes` is auto-computed from word count (200 wpm).
 *
 * Guarded list keeps server-managed counters out of mass assignment so a
 * forged admin form can't reset view counts or pre-poison body_html with
 * raw HTML. body_html is only written through the mutator (or the service).
 */
class BlogPost extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * @var array<int, string>
     */
    protected $guarded = [
        'id',
        'views_count',
        'body_html',
        'reading_minutes',
    ];

    /**
     * @var array<string, string>
     */
    protected $casts = [
        'published_at' => 'datetime',
        'scheduled_for' => 'datetime',
        'is_featured' => 'boolean',
        'views_count' => 'integer',
        'reading_minutes' => 'integer',
    ];

    public const STATUS_DRAFT = 'draft';

    public const STATUS_SCHEDULED = 'scheduled';

    public const STATUS_PUBLISHED = 'published';

    public const STATUS_ARCHIVED = 'archived';

    public const STATUSES = [
        self::STATUS_DRAFT,
        self::STATUS_SCHEDULED,
        self::STATUS_PUBLISHED,
        self::STATUS_ARCHIVED,
    ];

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    // ── Boot: slug autogen + body render trigger ──────────────────────

    protected static function booted(): void
    {
        static::saving(function (BlogPost $post): void {
            if (empty($post->slug) && ! empty($post->title)) {
                $base = Str::slug($post->title);
                $slug = $base ?: 'post';
                $i = 1;
                while (static::withTrashed()
                    ->where('slug', $slug)
                    ->where('id', '!=', $post->id ?? 0)
                    ->exists()
                ) {
                    $slug = $base.'-'.(++$i);
                }
                $post->slug = $slug;
            }
        });
    }

    // ── Relations ─────────────────────────────────────────────────────

    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'author_user_id');
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(BlogCategory::class, 'category_id');
    }

    /**
     * Movies referenced inside this article (pivot is admin-curated).
     * Pivot.sort_order drives the display order on the public page.
     */
    public function movies(): BelongsToMany
    {
        return $this->belongsToMany(Movie::class, 'blog_post_movie')
            ->withPivot('sort_order')
            ->orderBy('blog_post_movie.sort_order');
    }

    // ── Scopes ────────────────────────────────────────────────────────

    public function scopePublished(Builder $query): Builder
    {
        return $query
            ->where('status', self::STATUS_PUBLISHED)
            ->where('published_at', '<=', now());
    }

    public function scopeScheduled(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_SCHEDULED);
    }

    public function scopeDraft(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_DRAFT);
    }

    public function scopeFeatured(Builder $query): Builder
    {
        return $query->where('is_featured', true);
    }

    // ── Mutators / accessors ──────────────────────────────────────────

    /**
     * Stores the markdown source AND keeps the rendered HTML cache in
     * sync. Also recomputes reading_minutes from the word count (200wpm).
     *
     * Errors fall back to the raw markdown wrapped in <pre> so we never
     * persist a broken cache that would 500 the public detail page.
     */
    public function setBodyAttribute(?string $value): void
    {
        $value = (string) ($value ?? '');
        $this->attributes['body'] = $value;
        $this->attributes['body_html'] = self::renderMarkdown($value);
        $this->attributes['reading_minutes'] = self::estimateReadingMinutes($value);
    }

    /**
     * Public URL for the post — used by listing cards, RSS feed,
     * JSON-LD canonical, and email previews.
     */
    public function getUrlAttribute(): string
    {
        return route('blog.show', $this->slug);
    }

    /**
     * Resolved cover-image URL via the shared media disk (local public →
     * /storage/…, GCS in production). Absolute URLs pass through untouched;
     * null when the post has no cover — callers supply their own placeholder.
     */
    public function getCoverUrlAttribute(): ?string
    {
        return \App\Support\MediaDisk::url($this->cover_image);
    }

    // ── Helpers ───────────────────────────────────────────────────────

    public function isPublished(): bool
    {
        return $this->status === self::STATUS_PUBLISHED
            && $this->published_at !== null
            && $this->published_at->lte(now());
    }

    /**
     * Flip a draft / scheduled / archived post to published right now.
     * Idempotent — safe to call on an already-published post.
     */
    public function publish(): void
    {
        $now = now();
        $this->status = self::STATUS_PUBLISHED;
        $this->published_at = $this->published_at ?? $now;
        $this->save();
    }

    /**
     * Pure markdown→html. Kept static so BlogService and the mutator
     * can both reuse the same conversion + sanitisation rules.
     */
    public static function renderMarkdown(string $md): string
    {
        if ($md === '') {
            return '';
        }

        try {
            // Str::markdown ships with Laravel and uses league/commonmark
            // under the hood when present, plus a built-in fallback. We
            // pass html_input=escape so raw inline HTML in the markdown
            // source can't smuggle a <script> into the rendered page.
            return Str::markdown($md, [
                'html_input' => 'escape',
                'allow_unsafe_links' => false,
            ]);
        } catch (\Throwable $e) {
            Log::warning('BlogPost::renderMarkdown failed', ['error' => $e->getMessage()]);

            return '<pre>'.e($md).'</pre>';
        }
    }

    /**
     * Word-count → minutes at 200 wpm, rounded up. Floors at 1 min so
     * even a one-sentence post shows a sensible read-time pill.
     */
    public static function estimateReadingMinutes(string $md): int
    {
        $plain = trim(preg_replace('/\s+/', ' ', strip_tags(self::renderMarkdown($md))) ?? '');
        if ($plain === '') {
            return 0;
        }
        $words = str_word_count($plain);
        $minutes = (int) ceil($words / 200);

        return max(1, $minutes);
    }
}
